const REDUCE_MOTION=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const STORAGE={profiles:'myBlogAdminProfilesV1',active:'myBlogAdminActiveProfile',content:'myBlogAdminContentV1',device:'myBlogAdminDeviceKeyV1'};
const REPOS={test:'hb27bp49vk-source/myBlog-test',production:'hb27bp49vk-source/myBlog-prod'};
const labels={articles:'文章',notes:'短记',topics:'专题',accounts:'账号'};
const seed={articles:[{id:crypto.randomUUID(),title:'我为什么开始建立自己的 AI 工作流',summary:'工具越来越多以后，真正稀缺的不是工具，而是知道自己为什么使用它们。',body:'我想把 AI 放在一个更具体的位置：不是替我生活，而是帮助我把想法留下来、把重复工作变轻一点。',date:'2026-09-01',status:'published',updatedAt:Date.now()}],notes:[{id:crypto.randomUUID(),title:'真正能留下来的系统',summary:'真正能留下来的系统，不是最完整的那个，而是你愿意每天打开的那个。',body:'',date:'2026-08-30',status:'published',updatedAt:Date.now()}],topics:[{id:crypto.randomUUID(),title:'AI 工作流',summary:'从工具试用，到形成真正能帮我工作的个人方法。',body:'',date:'2026-09-01',status:'draft',updatedAt:Date.now()}]};
const state={view:'articles',selectedId:null,selectedProfileId:null,dirty:false,session:null,apiConnected:false,content:loadJSON(STORAGE.content,seed),profiles:loadJSON(STORAGE.profiles,[])};
const $=(selector)=>document.querySelector(selector);const $$=(selector)=>[...document.querySelectorAll(selector)];
function loadJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key))||structuredClone(fallback)}catch{return structuredClone(fallback)}}
function saveJSON(key,value){localStorage.setItem(key,JSON.stringify(value))}
function bytesToB64(bytes){let s='';bytes.forEach((b)=>s+=String.fromCharCode(b));return btoa(s)}
function b64ToBytes(value){return Uint8Array.from(atob(value),(c)=>c.charCodeAt(0))}
async function deriveKey(passcode,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(passcode),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:210000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptData(value,key){const iv=crypto.getRandomValues(new Uint8Array(12));const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(value)));return{iv:bytesToB64(iv),data:bytesToB64(new Uint8Array(encrypted))}}
async function decryptData(payload,key){const clear=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(payload.iv)},key,b64ToBytes(payload.data));return JSON.parse(new TextDecoder().decode(clear))}
async function getDeviceKey(){let raw=localStorage.getItem(STORAGE.device);if(!raw){raw=bytesToB64(crypto.getRandomValues(new Uint8Array(32)));localStorage.setItem(STORAGE.device,raw)}return crypto.subtle.importKey('raw',b64ToBytes(raw),{name:'AES-GCM'},false,['encrypt','decrypt'])}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('is-visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('is-visible'),2400)}
function openModal(el){el.hidden=false;REDUCE_MOTION?el.querySelector('input,select,button')?.focus():requestAnimationFrame(()=>el.querySelector('input,select,button')?.focus())}
function closeModal(el){el.hidden=true}
function currentItems(){return state.view==='accounts'?state.profiles:state.content[state.view]}
function persistContent(){saveJSON(STORAGE.content,state.content)}
function updateCounts(){$('#articleCount').textContent=state.content.articles.length;$('#noteCount').textContent=state.content.notes.length;$('#topicCount').textContent=state.content.topics.length;$('#accountCount').textContent=state.profiles.length}
function renderList(){const list=$('#contentList');const query=$('#searchInput').value.trim().toLowerCase();const filter=$('#statusFilter').value;if(state.view==='accounts'){const profiles=state.profiles.filter((p)=>(p.loginName+' '+p.profileName+' '+p.gistId).toLowerCase().includes(query));list.innerHTML=profiles.length?profiles.map((p)=>`<button class="content-item ${state.selectedProfileId===p.id?'is-active':''}" type="button" data-profile-id="${p.id}"><h3>${escapeHtml(p.profileName)}</h3><span class="status-chip">${state.session?.profileId===p.id?'已登录':'未登录'}</span><p>${escapeHtml(p.loginName)} · Gist ${p.gistId.slice(0,8)}…</p></button>`).join(''):'<div class="empty-list">还没有同步账号</div>';return}
const items=currentItems().filter((item)=>(filter==='all'||item.status===filter)&&(`${item.title} ${item.summary}`.toLowerCase().includes(query)));list.innerHTML=items.length?items.sort((a,b)=>b.updatedAt-a.updatedAt).map((item)=>`<button class="content-item ${state.selectedId===item.id?'is-active':''}" type="button" data-id="${item.id}"><h3>${escapeHtml(item.title||'未命名内容')}</h3><span class="status-chip ${item.status==='published'?'published':''}">${item.status==='published'?'已发布':'草稿'}</span><p>${escapeHtml(item.summary||'暂无摘要')}</p><time>${item.date||'未设置日期'}</time></button>`).join(''):'<div class="empty-list">没有符合条件的内容</div>'}
function escapeHtml(value=''){return value.replace(/[&<>'"]/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function selectItem(id){if(state.dirty&&!confirm('当前修改尚未保存，确定切换吗？'))return;state.selectedId=id;state.dirty=false;const item=currentItems().find((entry)=>entry.id===id);if(!item)return;$('#editorEmpty').hidden=true;$('#editorForm').hidden=false;$('#titleInput').value=item.title||'';$('#summaryInput').value=item.summary||'';$('#bodyInput').value=item.body||'';$('#dateInput').value=item.date||'';$('#contentStatusInput').value=item.status||'draft';$('#editorTitle').textContent=item.title||'未命名内容';setSaveState('尚未修改','');updatePreview();updateChecklist();renderList();$('#saveDraftButton').disabled=false}
function createItem(){if(state.view==='accounts'){openModal($('#accountModal'));return}const item={id:crypto.randomUUID(),title:'',summary:'',body:'',date:new Date().toISOString().slice(0,10),status:'draft',updatedAt:Date.now()};state.content[state.view].unshift(item);persistContent();selectItem(item.id);$('#titleInput').focus();updateCounts()}
function markDirty(){if(!state.selectedId)return;state.dirty=true;setSaveState('有未保存修改','is-dirty');updatePreview();updateChecklist()}
function setSaveState(text,className){const el=$('#saveState');el.textContent=text;el.className=`save-state ${className}`.trim()}
function saveDraft(){const item=currentItems().find((entry)=>entry.id===state.selectedId);if(!item)return;item.title=$('#titleInput').value.trim();item.summary=$('#summaryInput').value.trim();const normalizedBody=normalizeMarkdownImages($('#bodyInput').value);item.body=normalizedBody;$('#bodyInput').value=normalizedBody;item.date=$('#dateInput').value;item.status=$('#contentStatusInput').value;item.updatedAt=Date.now();state.dirty=false;persistContent();setSaveState('已保存到本机','is-saved');renderList();updatePreview();updateChecklist();syncContentToGist().catch(()=>toast('本地已保存，Gist 同步失败'))}
function normalizeMarkdownImages(value=''){return String(value).replace(/!\[([^\]]+)\]\s*!\[([^\]]*)\]\(([^)]+)\)/g,'![$1]($3)')}
function previewUrl(value=''){const url=String(value).trim();if(/[\u0000-\u001F\s]/.test(url))return'';if(/^\/assets\//.test(url))return '..'+url;if(/^\.\/assets\//.test(url))return '.'+url;return /^(https?:\/\/|\.\.\/)/.test(url)?url:''}
function renderMarkdownPreview(value=''){const lines=normalizeMarkdownImages(value).replace(/\r\n?/g,'\n').split('\n');const output=[];let index=0;const inline=(text)=>escapeHtml(text).replace(/!\[([^\]]*)\]\(([^)\s]+)\)/g,(_,alt,url)=>{const source=previewUrl(url);return source?`<img src="${source}" alt="${alt}" loading="lazy">`:'<span>图片地址无效</span>'}).replace(/\[([^\]]+)\]\(([^)\s]+)\)/g,(_,label,url)=>{const href=previewUrl(url);return href?`<a href="${href}" target="_blank" rel="noreferrer">${label}</a>`:label}).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/(?<!\*)\*([^*]+)\*(?!\*)/g,'<em>$1</em>');while(index<lines.length){const line=lines[index];if(!line.trim()){index++;continue}const heading=line.match(/^(#{1,3})\s+(.+)$/);if(heading){const level=heading[1].length+1;output.push(`<h${level}>${inline(heading[2])}</h${level}>`);index++;continue}const list=line.match(/^([-*+] |\d+\. )/);if(list){const ordered=/^\d+\. /.test(line);const pattern=ordered?/^\d+\.\s+(.+)$/:/^[-*+]\s+(.+)$/;const items=[];while(index<lines.length&&pattern.test(lines[index]))items.push(lines[index++].replace(pattern,'$1'));const tag=ordered?'ol':'ul';output.push(`<${tag}>${items.map((item)=>`<li>${inline(item)}</li>`).join('')}</${tag}>`);continue}const paragraph=[line];index++;while(index<lines.length&&lines[index].trim()&&!/^(#{1,3}\s|[-*+]\s+|\d+\.\s+)/.test(lines[index]))paragraph.push(lines[index++]);output.push(`<p>${paragraph.map(inline).join('<br>')}</p>`)}return output.join('')||'<p>正文排版预览会显示在这里。</p>'}
function updatePreview(){const title=$('#titleInput').value.trim()||'未命名内容';const summary=$('#summaryInput').value.trim()||'暂无摘要';$('#editorTitle').textContent=title;$('#previewTitle').textContent=title;$('#previewSummary').textContent=summary;$('#previewBody').innerHTML=renderMarkdownPreview($('#bodyInput').value);$('#previewDate').textContent=$('#dateInput').value||''}
function updateTarget(){const target=$('input[name="publishTarget"]:checked').value;$$('.target-option').forEach((label)=>label.classList.toggle('is-selected',label.querySelector('input').checked));$('#publishButton').textContent=state.apiConnected?`发布到${target==='test'?'测试库':'正式库'}`:`预演${target==='test'?'测试':'正式'}发布`;updateChecklist()}
function updateChecklist(){const checks=$$('#publishChecklist div');const item=state.selectedId?currentItems().find((entry)=>entry.id===state.selectedId):null;const values=[Boolean(state.session),Boolean(item&&$('#titleInput').value.trim()&&($('#bodyInput').value.trim()||state.view!=='articles')),Boolean(item&&!state.dirty),state.apiConnected];checks.forEach((el,index)=>el.classList.toggle('is-ok',values[index]));$('#publishButton').disabled=!(values[0]&&values[1]&&values[2])}
function setView(view){if(state.dirty&&!confirm('当前修改尚未保存，确定切换吗？'))return;state.view=view;state.selectedId=null;state.selectedProfileId=null;state.dirty=false;document.body.classList.toggle('account-view',view==='accounts');$('#accountDetail').hidden=true;$$('.nav-item').forEach((el)=>el.classList.toggle('is-active',el.dataset.view===view));$('#contentTitle').textContent=labels[view];$('#newContentButton').textContent=view==='accounts'?'＋ 新增账号':`＋ 新建${labels[view]}`;$('#searchInput').placeholder=view==='accounts'?'搜索账号':'搜索标题或摘要';$('#statusFilter').hidden=view==='accounts';$('#editorForm').hidden=true;$('#editorEmpty').hidden=false;$('#editorEmpty h2').textContent=view==='accounts'?'选择账号查看状态':'选择一项内容开始编辑';$('#editorEmpty p').textContent=view==='accounts'?'可以登录已有账号或新增同步账号。':'你也可以新建文章、短记或专题。';renderList();updateChecklist()}
function formatDateTime(value){return value?new Date(value).toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'}
function showAccountDetail(profileId){const profile=state.profiles.find((p)=>p.id===profileId);if(!profile)return;state.selectedProfileId=profileId;const loggedIn=state.session?.profileId===profileId;$('#editorEmpty').hidden=true;$('#editorForm').hidden=true;$('#accountDetail').hidden=false;$('#accountDetailAvatar').textContent=(profile.profileName||profile.loginName||'C').slice(0,1).toUpperCase();$('#accountDetailTitle').textContent=profile.profileName;$('#accountDetailState').textContent=loggedIn?'当前已登录 · Gist 已连接':'当前未登录';$('#detailLoginName').textContent=profile.loginName;$('#detailProfileName').textContent=profile.profileName;$('#detailGistId').textContent=profile.gistId;$('#detailCreatedAt').textContent=formatDateTime(profile.createdAt);$('#detailTrustedUntil').textContent=profile.trustedUntil>Date.now()?('信任至 '+formatDateTime(profile.trustedUntil)):'未开启或已过期';$('#openGistLink').href='https://gist.github.com/'+encodeURIComponent(profile.gistId);$('#accountLoginButton').hidden=loggedIn;$('#syncAccountButton').hidden=!loggedIn;$('#logoutAccountButton').hidden=!loggedIn;renderList()}
function loginSelectedProfile(){const profile=state.profiles.find((p)=>p.id===state.selectedProfileId);if(!profile)return;populateLoginProfiles();$('#loginProfileSelect').value=profile.id;openModal($('#loginModal'))}
async function copySelectedGistId(){const profile=state.profiles.find((p)=>p.id===state.selectedProfileId);if(!profile)return;try{await navigator.clipboard.writeText(profile.gistId);toast('Gist ID 已复制')}catch{toast('复制失败，请手动选择 Gist ID')}}
async function syncSelectedAccount(){if(state.session?.profileId!==state.selectedProfileId){loginSelectedProfile();return}const button=$('#syncAccountButton');button.disabled=true;button.textContent='同步中…';try{await pullContentFromGist();showAccountDetail(state.selectedProfileId)}catch(err){toast(err.message||'同步失败')}finally{button.disabled=false;button.textContent='立即同步'}}
function logoutSelectedAccount(){const profile=state.profiles.find((p)=>p.id===state.selectedProfileId);if(!profile||state.session?.profileId!==profile.id)return;state.session=null;state.apiConnected=false;profile.trustedPayload=null;profile.trustedUntil=0;localStorage.removeItem(STORAGE.active);saveJSON(STORAGE.profiles,state.profiles);updateAccountUi();showAccountDetail(profile.id);toast('已退出登录，本机信任已清除')}
function updateAccountUi(){const profile=state.session&&state.profiles.find((p)=>p.id===state.session.profileId);$('#accountTriggerLabel').textContent=profile?profile.profileName:(state.profiles.length?'登录账号':'新增账号');$('#connectionLabel').textContent=profile?'Gist 已连接':'本地草稿模式';document.querySelector('.status-dot').style.background=profile?'var(--up)':'var(--warn)';updateCounts();updateChecklist();renderList();if(state.view==='accounts'&&state.selectedProfileId)showAccountDetail(state.selectedProfileId)}
function populateLoginProfiles(){const select=$('#loginProfileSelect');select.innerHTML=state.profiles.map((p)=>`<option value="${p.id}">${escapeHtml(p.loginName)} · ${escapeHtml(p.profileName)}</option>`).join('')}
function openAccountFlow(){if(state.session){setView('accounts');showAccountDetail(state.session.profileId)}else if(state.profiles.length){populateLoginProfiles();openModal($('#loginModal'))}else openModal($('#accountModal'))}
async function verifyOrCreateGist(token,gistId,profileName){const headers={Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','Content-Type':'application/json'};if(gistId){const response=await fetch(`https://api.github.com/gists/${encodeURIComponent(gistId)}`,{headers});if(!response.ok)throw new Error('无法读取 Gist，请检查 Token 和 Gist ID');return gistId}const response=await fetch('https://api.github.com/gists',{method:'POST',headers,body:JSON.stringify({description:`${profileName} · myBlog admin`,public:false,files:{'myblog-admin.json':{content:JSON.stringify({version:1,createdAt:new Date().toISOString()})}}})});if(!response.ok)throw new Error('无法创建 Gist，请确认 Token 拥有 Gist 权限');return (await response.json()).id}
async function saveTrustedSession(profile,secrets,passcode){const deviceKey=await getDeviceKey();profile.trustedPayload=await encryptData({...secrets,passcode},deviceKey);profile.trustedUntil=Date.now()+7*24*60*60*1000}
async function submitAccount(event){event.preventDefault();const loginName=$('#loginNameInput').value.trim();const profileName=$('#profileNameInput').value.trim();const token=$('#gistTokenInput').value.trim();const passcode=$('#passcodeInput').value;const confirmCode=$('#passcodeConfirmInput').value;const error=$('#accountFormError');error.textContent='';if(!/^[a-zA-Z0-9_-]{3,32}$/.test(loginName)){error.textContent='登录账号需为 3 至 32 位字母、数字、下划线或短横线。';return}if(state.profiles.some((p)=>p.loginName.toLowerCase()===loginName.toLowerCase())){error.textContent='这个登录账号已经存在。';return}if(passcode.length<8){error.textContent='登录密钥至少需要 8 位。';return}if(passcode!==confirmCode){error.textContent='两次输入的登录密钥不一致。';return}const submit=event.submitter;submit.disabled=true;submit.textContent='正在绑定…';try{const gistId=await verifyOrCreateGist(token,$('#gistIdInput').value.trim(),profileName);const salt=crypto.getRandomValues(new Uint8Array(16));const key=await deriveKey(passcode,salt);const encrypted=await encryptData({token,gistId},key);const profile={id:crypto.randomUUID(),loginName,profileName,gistId,salt:bytesToB64(salt),encrypted,createdAt:Date.now()};if($('#trustDeviceInput').checked)await saveTrustedSession(profile,{token,gistId},passcode);state.profiles.push(profile);saveJSON(STORAGE.profiles,state.profiles);localStorage.setItem(STORAGE.active,profile.id);state.session={profileId:profile.id,token,gistId,key};if(state.view==='accounts')state.selectedProfileId=profile.id;closeModal($('#accountModal'));$('#accountForm').reset();updateAccountUi();await syncContentToGist();await checkApi();toast('账号已绑定并登录')}catch(err){error.textContent=err.message||'账号绑定失败'}finally{submit.disabled=false;submit.textContent='保存并登录'}}
async function submitLogin(event){event.preventDefault();const id=$('#loginProfileSelect').value;const profile=state.profiles.find((p)=>p.id===id);const error=$('#loginFormError');error.textContent='';try{const key=await deriveKey($('#loginPasscodeInput').value,b64ToBytes(profile.salt));const secrets=await decryptData(profile.encrypted,key);if($('#loginTrustDeviceInput').checked)await saveTrustedSession(profile,secrets,$('#loginPasscodeInput').value);saveJSON(STORAGE.profiles,state.profiles);localStorage.setItem(STORAGE.active,profile.id);state.session={profileId:profile.id,...secrets,key};closeModal($('#loginModal'));$('#loginForm').reset();await pullContentFromGist();updateAccountUi();await checkApi();toast('登录成功')}catch{error.textContent='登录密钥不正确，或账号数据已损坏。'}}
async function restoreTrustedSession(){const id=localStorage.getItem(STORAGE.active);const profile=state.profiles.find((p)=>p.id===id);if(!profile||!profile.trustedPayload||profile.trustedUntil<Date.now())return;try{const deviceKey=await getDeviceKey();const secrets=await decryptData(profile.trustedPayload,deviceKey);const key=await deriveKey(secrets.passcode,b64ToBytes(profile.salt));state.session={profileId:profile.id,token:secrets.token,gistId:secrets.gistId,key};await pullContentFromGist(false)}catch{profile.trustedPayload=null;profile.trustedUntil=0;saveJSON(STORAGE.profiles,state.profiles)}}
async function syncContentToGist(){if(!state.session?.token||!state.session?.gistId)return;let payload={version:1,updatedAt:new Date().toISOString(),content:state.content};if(state.session.key)payload={version:1,encrypted:true,payload:await encryptData(state.content,state.session.key)};const response=await fetch(`https://api.github.com/gists/${state.session.gistId}`,{method:'PATCH',headers:{Authorization:`Bearer ${state.session.token}`,Accept:'application/vnd.github+json','Content-Type':'application/json'},body:JSON.stringify({files:{'myblog-admin.json':{content:JSON.stringify(payload)}}})});if(!response.ok)throw new Error('Gist 同步失败');toast('草稿已保存并同步')}
async function pullContentFromGist(showToast=true){if(!state.session?.token||!state.session?.gistId)return;const response=await fetch(`https://api.github.com/gists/${state.session.gistId}`,{headers:{Authorization:`Bearer ${state.session.token}`,Accept:'application/vnd.github+json'}});if(!response.ok)throw new Error('Gist 读取失败');const gist=await response.json();const file=gist.files?.['myblog-admin.json'];if(!file)return;const payload=JSON.parse(file.content);if(payload.encrypted&&payload.payload&&state.session.key)state.content=await decryptData(payload.payload,state.session.key);else if(payload.content)state.content=payload.content;persistContent();updateCounts();renderList();if(showToast)toast('已从 Gist 读取最新内容')}
function toBlogContent(){const published=(items)=>items.filter((item)=>item.status==='published');return{articles:published(state.content.articles).map((item)=>({date:(item.date||'').replaceAll('-','.'),type:'文章 / 博客',title:item.title,summary:item.summary||'',body:item.body||''})),notes:published(state.content.notes).map((item,index)=>({date:(item.date||'').replaceAll('-','.'),label:item.title||('THOUGHT / '+String(index+1).padStart(3,'0')),text:item.body||item.summary||item.title||''})),topics:published(state.content.topics).map((item)=>({title:item.title,text:item.body||item.summary||'',status:'持续积累'}))}}
function buildContentFile(){return 'window.blogContent = '+JSON.stringify(toBlogContent(),null,2).replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029')+';\n'}
async function verifyPublishToken(token,gistId){const headers={Authorization:'Bearer '+token,Accept:'application/vnd.github+json'};for(const repo of Object.values(REPOS)){const response=await fetch('https://api.github.com/repos/'+repo,{headers});if(!response.ok)throw new Error('Token 无法访问 '+repo);const info=await response.json();if(!info.permissions?.push)throw new Error('Token 对 '+repo+' 没有写入权限')}if(gistId){const gist=await fetch('https://api.github.com/gists/'+encodeURIComponent(gistId),{headers});if(!gist.ok)throw new Error('Token 无法访问当前 Gist，请开启 Gists: Read and write')}return true}
async function publishContentToRepository(target){if(!state.session?.token)throw new Error('请先登录同步账号');const repo=REPOS[target];const path='content.js';const headers={Authorization:'Bearer '+state.session.token,Accept:'application/vnd.github+json','Content-Type':'application/json'};const url='https://api.github.com/repos/'+repo+'/contents/'+path;const current=await fetch(url+'?ref=main',{headers});let sha;if(current.ok)sha=(await current.json()).sha;else if(current.status!==404)throw new Error('无法读取目标仓库，请检查 Token 权限');const content=bytesToB64(new TextEncoder().encode(buildContentFile()));const response=await fetch(url,{method:'PUT',headers,body:JSON.stringify({message:'content: publish from myBlog admin',content,branch:'main',...(sha?{sha}:{})})});if(!response.ok){if(response.status===401||response.status===403)throw new Error('Fine-grained Token 没有目标仓库 Contents: Read and write 权限');const detail=await response.json().catch(()=>({}));throw new Error(detail.message||'仓库写入失败')}return response.json()}
async function checkApi(){state.apiConnected=Boolean(state.session?.token);updateTarget()}
function openPublishConfirm(){const target=$('input[name="publishTarget"]:checked').value;const item=currentItems().find((entry)=>entry.id===state.selectedId);$('#confirmRepository').textContent=REPOS[target];$('#confirmContentTitle').textContent=item?.title||'未命名内容';$('#publishConfirmCopy').textContent=target==='production'?'这次修改会进入正式博客，请核对目标和内容。':'这次修改只进入测试博客，发布后请先检查页面。';$('#productionConfirmField').hidden=target!=='production';$('#productionConfirmInput').value='';$('#publishFormError').textContent='';$('#confirmPublishButton').className=`button ${target==='production'?'button-danger':'button-primary'}`;openModal($('#publishModal'))}
async function confirmPublish(){const target=$('input[name="publishTarget"]:checked').value;if(target==='production'&&$('#productionConfirmInput').value.trim()!=='正式发布'){$('#publishFormError').textContent='请输入“正式发布”后再继续。';return}if(!state.session?.token){$('#publishFormError').textContent='请先登录具有仓库写入权限的账号。';return}const button=$('#confirmPublishButton');button.disabled=true;button.textContent='正在发布…';try{const result=await publishContentToRepository(target);closeModal($('#publishModal'));state.apiConnected=true;updateTarget();toast('已发布到'+(target==='test'?'测试库':'正式库')+' · '+result.commit.sha.slice(0,7))}catch(err){$('#publishFormError').textContent=err.message}finally{button.disabled=false;button.textContent='确认发布'}}
async function submitCredential(event){event.preventDefault();const token=$('#publishTokenInput').value.trim();const error=$('#credentialFormError');const profile=state.profiles.find((p)=>p.id===state.selectedProfileId);error.textContent='';if(!profile||state.session?.profileId!==profile.id){error.textContent='请先登录当前账号。';return}const button=event.submitter;button.disabled=true;button.textContent='正在验证…';try{await verifyPublishToken(token,profile.gistId);profile.encrypted=await encryptData({token,gistId:profile.gistId},state.session.key);profile.trustedPayload=null;profile.trustedUntil=0;state.session.token=token;saveJSON(STORAGE.profiles,state.profiles);closeModal($('#credentialModal'));$('#credentialForm').reset();await checkApi();showAccountDetail(profile.id);toast('发布凭据已更新，本机信任已清除')}catch(err){error.textContent=err.message||'Token 验证失败'}finally{button.disabled=false;button.textContent='验证并保存'}}
function bindEvents(){$$('.nav-item').forEach((button)=>button.addEventListener('click',()=>setView(button.dataset.view)));$('#newContentButton').addEventListener('click',createItem);$('#contentList').addEventListener('click',(event)=>{const item=event.target.closest('[data-id]');if(item)selectItem(item.dataset.id);const profile=event.target.closest('[data-profile-id]');if(profile)showAccountDetail(profile.dataset.profileId)});$('#searchInput').addEventListener('input',renderList);$('#statusFilter').addEventListener('change',renderList);$('#editorForm').addEventListener('input',markDirty);$('#saveDraftButton').addEventListener('click',saveDraft);$$('input[name="publishTarget"]').forEach((input)=>input.addEventListener('change',updateTarget));$('#publishButton').addEventListener('click',openPublishConfirm);$('#accountTrigger').addEventListener('click',openAccountFlow);$('#copyGistIdButton').addEventListener('click',copySelectedGistId);$('#accountLoginButton').addEventListener('click',loginSelectedProfile);$('#syncAccountButton').addEventListener('click',syncSelectedAccount);$('#logoutAccountButton').addEventListener('click',logoutSelectedAccount);$('#updateCredentialButton').addEventListener('click',()=>{if(state.session?.profileId!==state.selectedProfileId){loginSelectedProfile();return}openModal($('#credentialModal'))});$('#credentialForm').addEventListener('submit',submitCredential);$('#accountForm').addEventListener('submit',submitAccount);$('#loginForm').addEventListener('submit',submitLogin);$('#addAccountFromLogin').addEventListener('click',()=>{closeModal($('#loginModal'));openModal($('#accountModal'))});$('#confirmPublishButton').addEventListener('click',confirmPublish);[['closeAccountModal','accountModal'],['cancelAccountButton','accountModal'],['closeLoginModal','loginModal'],['closeCredentialModal','credentialModal'],['cancelCredentialButton','credentialModal'],['closePublishModal','publishModal'],['cancelPublishButton','publishModal'],['cancelPublishButton','publishModal']].forEach(([button,modal])=>$('#'+button)?.addEventListener('click',()=>closeModal($('#'+modal))));$$('.modal-backdrop').forEach((backdrop)=>backdrop.addEventListener('click',(event)=>{if(event.target===backdrop)closeModal(backdrop)}));document.addEventListener('keydown',(event)=>{if(event.key==='Escape')$$('.modal-backdrop').forEach(closeModal);if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();if(state.selectedId)saveDraft()}});window.addEventListener('beforeunload',(event)=>{if(state.dirty){event.preventDefault();event.returnValue=''}})}
async function init(){bindEvents();updateCounts();renderList();await restoreTrustedSession();updateAccountUi();checkApi();if(!state.profiles.length)openModal($('#accountModal'))}
init();
function insertMarkdown(kind){const input=$('#bodyInput');const start=input.selectionStart;const end=input.selectionEnd;let text='';if(kind==='heading')text='## 小标题';if(kind==='link'){const label=prompt('链接文字');const url=prompt('链接地址（https://...）');if(!label||!url)return;text=`[${label}](${url})`}if(kind==='image'){const alt=prompt('图片说明（可留空）')||'图片';const url=prompt('图片地址（https://... 或 ./assets/...）');if(!url)return;text=`![${alt}](${url})`}input.setRangeText(text,start,end,'end');input.focus();input.dispatchEvent(new Event('input',{bubbles:true}))}
function fileAsBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)})}
async function uploadMarkdownImage(){const file=$('#markdownImageInput').files[0];if(!file)return;if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type)){toast('仅支持 PNG、JPG、WebP 或 GIF 图片');return}if(file.size>4*1024*1024){toast('图片请控制在 4MB 以内');return}if(!state.session?.token){toast('请先登录具有仓库写入权限的账号');return}const target=$('input[name="publishTarget"]:checked').value;const button=$('#uploadImageButton');button.disabled=true;button.textContent='上传中…';try{const ext=(file.name.match(/\.[a-z0-9]+$/i)||['.png'])[0].toLowerCase();const base=file.name.replace(/\.[^.]+$/,'').replace(/[^a-z0-9_-]+/gi,'-').replace(/^-+|-+$/g,'').slice(0,48)||'image';const path=`assets/uploads/${Date.now()}-${base}${ext}`;const repo=REPOS[target];const response=await fetch(`https://api.github.com/repos/${repo}/contents/${path}`,{method:'PUT',headers:{Authorization:'Bearer '+state.session.token,Accept:'application/vnd.github+json','Content-Type':'application/json'},body:JSON.stringify({message:'asset: upload image from myBlog admin',content:await fileAsBase64(file),branch:'main'})});if(!response.ok)throw new Error(response.status===401||response.status===403?'Token 没有当前仓库的 Contents: Read and write 权限':'图片上传失败');const body=$('#bodyInput');const start=body.selectionStart;const end=body.selectionEnd;const before=body.value.slice(0,start);const dangling=before.match(/!\[([^\]]*)\]$/);const alt=dangling?.[1]||file.name;const markdown='!['+alt+'](./'+path+')';body.setRangeText(markdown,dangling&&start===end?start-dangling[0].length:start,end,'end');body.focus();body.dispatchEvent(new Event('input',{bubbles:true}));toast(`图片已上传到${target==='test'?'测试库':'正式库'}并插入正文`)}catch(error){toast(error.message||'图片上传失败')}finally{button.disabled=false;button.textContent='上传图片';$('#markdownImageInput').value=''}}
$$('.markdown-insert').forEach((button)=>button.addEventListener('click',()=>insertMarkdown(button.dataset.markdown)));
$('#uploadImageButton').addEventListener('click',()=>$('#markdownImageInput').click());
$('#markdownImageInput').addEventListener('change',uploadMarkdownImage);






